/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tactfactory.mongocrawler;

import com.mongodb.client.MongoDatabase;
import com.tactfactory.mongocrawler.database.MongoService;

public class App {
  public String getGreeting() {
    return "Hello world.";
  }

  public static void main(String[] args) throws Exception {
    System.out.println(new App().getGreeting());

    String host = "127.0.0.1";
    Integer port = 27017;
    String database = "";

    for (int i = 0; i < args.length; i++) {
      if (args[i].startsWith("--")) {
        if (args[i].equals("--host")) {
          if (i + 1 < args.length && !args[i + 1].startsWith("--")) {
            host = args[i+1];
          }else {
            throw new Exception("--host not defined");
          }
        }
        if (args[i].equals("--port")) {
          if (i + 1 < args.length && !args[i + 1].startsWith("--")) {
            try {
              port = Integer.parseInt(args[i+1]);
            } catch (NumberFormatException e) {
              throw e;
            }
          }else {
            throw new Exception("--port not defined");
          }
        }
        if (args[i].equals("--db")) {
          if (i + 1 < args.length && !args[i + 1].startsWith("--")) {
            database = args[i+1];
          }else {
            throw new Exception("--db not defined");
          }
        }
      }
    }

    MongoService service = new MongoService(host, port);
    MongoDatabase db = service.getMongoClient().getDatabase(database);
    for (String string : db.listCollectionNames()) {
      System.out.println(string);
    }


    System.out.println("Ended");
  }
}
